services:
  agcode:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "10002:8000"
    environment:
      PRODUCT_ENV: ${PRODUCT_ENV}
      CLIENT_ID: ${CLIENT_ID}
      STORAGE_SERVICE_URL : ${STORAGE_SERVICE_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      #KEYCLOAK_AUDIENCE: ””
      SQL_TYPE: ${SQL_TYPE}
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DB: ${SQL_DB}
      REDIS_URL: ${REDIS_URL}
      IMAGE_NAME_CODER_PRO: ${IMAGE_NAME_CODER_PRO}
      IMAGE_NAME_CODER_NOOB: ${IMAGE_NAME_CODER_NOOB}
      SESSION_RUNTIME_MODE: ${SESSION_RUNTIME_MODE}
      LOCAL_IMAGE_NAME_CODER_PRO: ${LOCAL_IMAGE_NAME_CODER_PRO}
      LOCAL_IMAGE_NAME_CODER_NOOB: ${LOCAL_IMAGE_NAME_CODER_NOOB}
      WORKER_BUILD_ID: ${WORKER_BUILD_ID}
      SESSION_REMOTE_CONFIG_PATH: ${SESSION_REMOTE_CONFIG_PATH}
      SESSION_K8S_NAMESPACE: ${SESSION_K8S_NAMESPACE}
      SESSION_K8S_STORAGE_CLASS: ${SESSION_K8S_STORAGE_CLASS}
      SESSION_K8S_PVC_SIZE: ${SESSION_K8S_PVC_SIZE}
      SESSION_SCHEDULING_TIMEOUT_SECONDS: ${SESSION_SCHEDULING_TIMEOUT_SECONDS}
      SESSION_WORKER_PORT: ${SESSION_WORKER_PORT}
      SESSION_WORKER_SOCKETIO_PATH: ${SESSION_WORKER_SOCKETIO_PATH}
      SESSION_NOOB_RUNTIME_CLASS: ${SESSION_NOOB_RUNTIME_CLASS}
      SESSION_NOOB_MOUNT_PATH: ${SESSION_NOOB_MOUNT_PATH}
      HATCHET_CLIENT_TOKEN: ${HATCHET_CLIENT_TOKEN}
      HATCHET_CLIENT_HOST_PORT: ${HATCHET_CLIENT_HOST_PORT}
      HATCHET_CLIENT_SERVER_URL: ${HATCHET_CLIENT_SERVER_URL}
      HATCHET_CLIENT_TLS_STRATEGY: "none"
