services:
  agcode:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "10002:8000"
    environment:
      PRODUCT_ENV: ${PRODUCT_ENV}
      CLIENT_ID: ${CLIENT_ID}
      STORAGE_SERVICE_URL : ${STORAGE_SERVICE_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      #KEYCLOAK_AUDIENCE: ””
      SQL_TYPE: ${SQL_TYPE}
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DB: ${SQL_DB}
      IMAGE_NAME_CODER_PRO: ${IMAGE_NAME_CODER_PRO}
      IMAGE_NAME_CODER_NOOB: ${IMAGE_NAME_CODER_NOOB}
      HATCHET_CLIENT_TOKEN: ${HATCHET_CLIENT_TOKEN}
      HATCHET_CLIENT_HOST_PORT: ${HATCHET_CLIENT_HOST_PORT}
      HATCHET_CLIENT_SERVER_URL: ${HATCHET_CLIENT_SERVER_URL}
      HATCHET_CLIENT_TLS_STRATEGY: "none"
