services:
  coder_pro:
    image: iwaag/agoffice-coder-pro:latest
    build:
      context: ../..
      dockerfile: deploy/docker/worker-pro.Dockerfile
    ports:
      - "11001:8000"
    environment:
      PRODUCT_ENV: ${PRODUCT_ENV}
      CLIENT_ID: ${CLIENT_ID}
      WORKSPACE_ROOT: ${WORKSPACE_ROOT}
      AGENT_PROVIDER: ${AGENT_PROVIDER}
      HATCHET_CLIENT_TOKEN: ${HATCHET_CLIENT_TOKEN}
      HATCHET_CLIENT_HOST_PORT: ${HATCHET_CLIENT_HOST_PORT}
      HATCHET_CLIENT_SERVER_URL: ${HATCHET_CLIENT_SERVER_URL}
      HATCHET_CLIENT_TLS_STRATEGY: "none"
      #CODEX_API_KEY: ${CODEX_API_KEY}

  coder_noob:
    image: iwaag/agoffice-coder-noob:latest
    build:
      context: ../..
      dockerfile: deploy/docker/worker-noob.Dockerfile
    environment:
      NOOB_SESSION_ROOT: /mnt/session

 
